import type { Question } from './types';
import { Difficulty, Company } from './types';

export const DEFAULT_QUESTIONS: Question[] = [
  // Arrays & Hashing
  {
    id: "1",
    title: "Contains Duplicate",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "Given an integer array `nums`, return `true` if any value appears at least twice in the array, and return `false` if every element is distinct.",
  },
  {
    id: "2",
    title: "Valid Anagram",
    difficulty: Difficulty.Easy,
    company: Company.Amazon,
    problemStatement: "Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise. An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.",
  },
  {
    id: "3",
    title: "Two Sum",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.",
  },
  {
    id: "4",
    title: "Group Anagrams",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given an array of strings `strs`, group the anagrams together. You can return the answer in any order.",
  },
  {
    id: "5",
    title: "Top K Frequent Elements",
    difficulty: Difficulty.Medium,
    company: Company.Netflix,
    problemStatement: "Given an integer array `nums` and an integer `k`, return the `k` most frequent elements. You may return the answer in any order.",
  },
  {
    id: "6",
    title: "Product of Array Except Self",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "Given an integer array `nums`, return an array `answer` such that `answer[i]` is equal to the product of all the elements of `nums` except `nums[i]`. The product of any prefix or suffix of `nums` is guaranteed to fit in a 32-bit integer. You must write an algorithm that runs in O(n) time and without using the division operation.",
  },
  {
    id: "7",
    title: "Valid Sudoku",
    difficulty: Difficulty.Medium,
    company: Company.General,
    problemStatement: "Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules: Each row must contain the digits 1-9 without repetition. Each column must contain the digits 1-9 without repetition. Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.",
  },
  {
    id: "8",
    title: "Encode and Decode Strings",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "Design an algorithm to encode a list of strings to a string. The encoded string is then sent over the network and is decoded back to the original list of strings. Please implement encode and decode.",
  },
  {
    id: "9",
    title: "Longest Consecutive Sequence",
    difficulty: Difficulty.Medium,
    company: Company.Adobe,
    problemStatement: "Given an unsorted array of integers `nums`, return the length of the longest consecutive elements sequence. You must write an algorithm that runs in O(n) time.",
  },
  // Two Pointers
  {
    id: "10",
    title: "Valid Palindrome",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers. Given a string `s`, return `true` if it is a palindrome, or `false` otherwise.",
  },
  {
    id: "11",
    title: "Two Sum II - Input Array Is Sorted",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Given a 1-indexed array of integers `numbers` that is already sorted in non-decreasing order, find two numbers such that they add up to a specific `target` number. Let these two numbers be `numbers[index1]` and `numbers[index2]` where `1 <= index1 < index2 <= numbers.length`. Return the indices of the two numbers, `index1` and `index2`, added by one as an integer array `[index1, index2]` of length 2.",
  },
  {
    id: "12",
    title: "3Sum",
    difficulty: Difficulty.Medium,
    company: Company.Apple,
    problemStatement: "Given an integer array `nums`, return all the triplets `[nums[i], nums[j], nums[k]]` such that `i != j`, `i != k`, and `j != k`, and `nums[i] + nums[j] + nums[k] == 0`. Notice that the solution set must not contain duplicate triplets.",
  },
  {
    id: "13",
    title: "Container With Most Water",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "You are given an integer array `height` of length `n`. There are `n` vertical lines drawn such that the two endpoints of the `i`-th line are `(i, 0)` and `(i, height[i])`. Find two lines that together with the x-axis form a container, such that the container contains the most water. Return the maximum amount of water a container can store.",
  },
  {
    id: "14",
    title: "Trapping Rain Water",
    difficulty: Difficulty.Hard,
    company: Company.Microsoft,
    problemStatement: "Given `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
  },
  // Sliding Window
  {
    id: "15",
    title: "Best Time to Buy and Sell Stock",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "You are given an array `prices` where `prices[i]` is the price of a given stock on the `i`-th day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.",
  },
  {
    id: "16",
    title: "Longest Substring Without Repeating Characters",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given a string `s`, find the length of the longest substring without repeating characters.",
  },
  {
    id: "17",
    title: "Longest Repeating Character Replacement",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "You are given a string `s` and an integer `k`. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most `k` times. Return the length of the longest substring containing the same letter you can get after performing the above operations.",
  },
  {
    id: "18",
    title: "Permutation in String",
    difficulty: Difficulty.Medium,
    company: Company.Netflix,
    problemStatement: "Given two strings `s1` and `s2`, return `true` if `s2` contains a permutation of `s1`, or `false` otherwise. In other words, return `true` if one of `s1`'s permutations is the substring of `s2`.",
  },
  {
    id: "19",
    title: "Minimum Window Substring",
    difficulty: Difficulty.Hard,
    company: Company.Amazon,
    problemStatement: "Given two strings `s` and `t` of lengths `m` and `n` respectively, return the minimum window substring of `s` such that every character in `t` (including duplicates) is included in the window. If there is no such substring, return the empty string `\"\"`.",
  },
  {
    id: "20",
    title: "Sliding Window Maximum",
    difficulty: Difficulty.Hard,
    company: Company.Microsoft,
    problemStatement: "You are given an array of integers `nums`, there is a sliding window of size `k` which is moving from the very left of the array to the very right. You can only see the `k` numbers in the window. Each time the sliding window moves right by one position. Return the max sliding window.",
  },
  // Stack
  {
    id: "21",
    title: "Valid Parentheses",
    difficulty: Difficulty.Easy,
    company: Company.Google,
    problemStatement: "Given a string `s` containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid. An input string is valid if: Open brackets must be closed by the same type of brackets. Open brackets must be closed in the correct order. Every close bracket has a corresponding open bracket of the same type.",
  },
  {
    id: "22",
    title: "Min Stack",
    difficulty: Difficulty.Medium,
    company: Company.General,
    problemStatement: "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time. Implement the `MinStack` class.",
  },
  {
    id: "23",
    title: "Evaluate Reverse Polish Notation",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Evaluate the value of an arithmetic expression in Reverse Polish Notation. Valid operators are `+`, `-`, `*`, `/`. Each operand may be an integer or another expression.",
  },
  {
    id: "24",
    title: "Generate Parentheses",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given `n` pairs of parentheses, write a function to generate all combinations of well-formed parentheses.",
  },
  {
    id: "25",
    title: "Daily Temperatures",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "Given an array of integers `temperatures` represents the daily temperatures, return an array `answer` such that `answer[i]` is the number of days you have to wait after the `i`-th day to get a warmer temperature. If there is no future day for which this is possible, keep `answer[i] == 0` instead.",
  },
  {
    id: "26",
    title: "Car Fleet",
    difficulty: Difficulty.Medium,
    company: Company.Netflix,
    problemStatement: "There are `n` cars going to the same destination along a one-lane road. The destination is `target` miles away. You are given two integer arrays `position` and `speed`, both of length `n`, where `position[i]` is the position of the `i`-th car and `speed[i]` is the speed of the `i`-th car (in miles per hour). Return the number of car fleets that will arrive at the destination.",
  },
  {
    id: "27",
    title: "Largest Rectangle in Histogram",
    difficulty: Difficulty.Hard,
    company: Company.Microsoft,
    problemStatement: "Given an array of integers `heights` representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
  },
  // Binary Search
  {
    id: "28",
    title: "Binary Search",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "Given an array of integers `nums` which is sorted in ascending order, and an integer `target`, write a function to search `target` in `nums`. If `target` exists, then return its index. Otherwise, return -1. You must write an algorithm with O(log n) runtime complexity.",
  },
  {
    id: "29",
    title: "Search a 2D Matrix",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "You are given an `m x n` integer matrix `matrix` with the following two properties: Each row is sorted in non-decreasing order. The first integer of each row is greater than the last integer of the previous row. Given an integer `target`, return `true` if `target` is in `matrix` or `false` otherwise. You must write a solution in O(log(m * n)) time complexity.",
  },
  {
    id: "30",
    title: "Koko Eating Bananas",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "Koko loves to eat bananas. There are `n` piles of bananas, the `i`-th pile has `piles[i]` bananas. The guards have gone and will come back in `h` hours. Koko can decide her bananas-per-hour eating speed of `k`. Each hour, she chooses some pile of bananas and eats `k` bananas from that pile. If the pile has less than `k` bananas, she eats all of them instead and will not eat any more bananas during this hour. Return the minimum integer `k` such that she can eat all the bananas within `h` hours.",
  },
  {
    id: "31",
    title: "Search in Rotated Sorted Array",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "There is an integer array `nums` sorted in ascending order (with distinct values). Prior to being passed to your function, `nums` is possibly rotated at an unknown pivot index `k`. Given the array `nums` after the possible rotation and an integer `target`, return the index of `target` if it is in `nums`, or -1 if it is not in `nums`. You must write an algorithm with O(log n) runtime complexity.",
  },
  {
    id: "32",
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "Suppose an array of length `n` sorted in ascending order is rotated between 1 and `n` times. Given the sorted rotated array `nums` of unique elements, return the minimum element of this array. You must write an algorithm that runs in O(log n) time.",
  },
  {
    id: "33",
    title: "Time Based Key-Value Store",
    difficulty: Difficulty.Medium,
    company: Company.Apple,
    problemStatement: "Design a time-based key-value data structure that can store multiple values for the same key at different time stamps and retrieve the key's value at a certain timestamp. Implement the `TimeMap` class.",
  },
  {
    id: "34",
    title: "Median of Two Sorted Arrays",
    difficulty: Difficulty.Hard,
    company: Company.Adobe,
    problemStatement: "Given two sorted arrays `nums1` and `nums2` of size `m` and `n` respectively, return the median of the two sorted arrays. The overall run time complexity should be O(log (m+n)).",
  },
  // Linked List
  {
    id: "35",
    title: "Reverse Linked List",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "Given the `head` of a singly linked list, reverse the list, and return the reversed list.",
  },
  {
    id: "36",
    title: "Merge Two Sorted Lists",
    difficulty: Difficulty.Easy,
    company: Company.Microsoft,
    problemStatement: "You are given the heads of two sorted linked lists `list1` and `list2`. Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists. Return the head of the merged linked list.",
  },
  {
    id: "37",
    title: "Reorder List",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "You are given the head of a singly linked-list. The list can be represented as: L0 → L1 → … → Ln - 1 → Ln. Reorder the list to be on the following form: L0 → Ln → L1 → Ln - 1 → L2 → Ln - 2 → … You may not modify the values in the list's nodes. Only nodes themselves may be changed.",
  },
  {
    id: "38",
    title: "Remove Nth Node From End of List",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given the `head` of a linked list, remove the `n`-th node from the end of the list and return its head.",
  },
  {
    id: "39",
    title: "Copy List with Random Pointer",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "A linked list of length `n` is given such that each node contains an additional random pointer, which could point to any node in the list, or `null`. Construct a deep copy of the list. The deep copy should consist of exactly `n` brand new nodes, where each new node has its value set to the value of its corresponding original node.",
  },
  {
    id: "40",
    title: "Add Two Numbers",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.",
  },
  {
    id: "41",
    title: "Linked List Cycle",
    difficulty: Difficulty.Easy,
    company: Company.Adobe,
    problemStatement: "Given `head`, the head of a linked list, determine if the linked list has a cycle in it. There is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the `next` pointer. Return `true` if there is a cycle, `false` otherwise.",
  },
  {
    id: "42",
    title: "Find the Duplicate Number",
    difficulty: Difficulty.Medium,
    company: Company.Apple,
    problemStatement: "Given an array of integers `nums` containing `n + 1` integers where each integer is in the range `[1, n]` inclusive. There is only one repeated number in `nums`, return this repeated number. You must solve the problem without modifying the array `nums` and uses only constant extra space.",
  },
  {
    id: "43",
    title: "LRU Cache",
    difficulty: Difficulty.Medium,
    company: Company.Netflix,
    problemStatement: "Design a data structure that follows the constraints of a Least Recently Used (LRU) cache. Implement the `LRUCache` class: `LRUCache(int capacity)` initializes the LRU cache with positive size capacity. `int get(int key)` returns the value of the key if the key exists, otherwise return -1. `void put(int key, int value)` updates the value of the key if the key exists. Otherwise, add the key-value pair to the cache. If the number of keys exceeds the capacity from this operation, evict the least recently used key.",
  },
  {
    id: "44",
    title: "Merge K Sorted Lists",
    difficulty: Difficulty.Hard,
    company: Company.Amazon,
    problemStatement: "You are given an array of `k` linked-lists `lists`, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.",
  },
  {
    id: "45",
    title: "Reverse Nodes in k-Group",
    difficulty: Difficulty.Hard,
    company: Company.Google,
    problemStatement: "Given the `head` of a linked list, reverse the nodes of the list `k` at a time, and return the modified list.",
  },
  // Trees
  {
    id: "46",
    title: "Invert Binary Tree",
    difficulty: Difficulty.Easy,
    company: Company.Google,
    problemStatement: "Given the `root` of a binary tree, invert the tree, and return its root.",
  },
  {
    id: "47",
    title: "Maximum Depth of Binary Tree",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "Given the `root` of a binary tree, return its maximum depth. A binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.",
  },
  {
    id: "48",
    title: "Diameter of Binary Tree",
    difficulty: Difficulty.Easy,
    company: Company.Meta,
    problemStatement: "Given the `root` of a binary tree, return the length of the diameter of the tree. The diameter of a binary tree is the length of the longest path between any two nodes in a tree. This path may or may not pass through the root.",
  },
  {
    id: "49",
    title: "Balanced Binary Tree",
    difficulty: Difficulty.Easy,
    company: Company.Amazon,
    problemStatement: "Given a binary tree, determine if it is height-balanced. A height-balanced binary tree is a binary tree in which the depth of the two subtrees of every node never differs by more than one.",
  },
  {
    id: "50",
    title: "Same Tree",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "Given the roots of two binary trees `p` and `q`, write a function to check if they are the same or not. Two binary trees are considered the same if they are structurally identical, and the nodes have the same value.",
  },
  {
    id: "51",
    title: "Subtree of Another Tree",
    difficulty: Difficulty.Easy,
    company: Company.Microsoft,
    problemStatement: "Given the roots of two binary trees `root` and `subRoot`, return `true` if there is a subtree of `root` with the same structure and node values of `subRoot` and `false` otherwise.",
  },
  {
    id: "52",
    title: "Lowest Common Ancestor of a BST",
    difficulty: Difficulty.Easy,
    company: Company.Microsoft,
    problemStatement: "Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.",
  },
  {
    id: "53",
    title: "Binary Tree Level Order Traversal",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given the `root` of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).",
  },
  {
    id: "54",
    title: "Binary Tree Right Side View",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Given the `root` of a binary tree, imagine yourself standing on the right side of it, return the values of the nodes you can see ordered from top to bottom.",
  },
  {
    id: "55",
    title: "Count Good Nodes in Binary Tree",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "Given a binary tree `root`, a node X in the tree is named good if in the path from root to X there are no nodes with a value greater than X. Return the number of good nodes in the binary tree.",
  },
  {
    id: "56",
    title: "Validate Binary Search Tree",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Given the `root` of a binary tree, determine if it is a valid binary search tree (BST).",
  },
  {
    id: "57",
    title: "Kth Smallest Element in a BST",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given the `root` of a binary search tree, and an integer `k`, return the `k`th smallest value (1-indexed) of all the values of the nodes in the tree.",
  },
  {
    id: "58",
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "Given two integer arrays `preorder` and `inorder` where `preorder` is the preorder traversal of a binary tree and `inorder` is the inorder traversal of the same tree, construct and return the binary tree.",
  },
  {
    id: "59",
    title: "Binary Tree Maximum Path Sum",
    difficulty: Difficulty.Hard,
    company: Company.Google,
    problemStatement: "A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. A node can only appear in the sequence at most once. Note that the path does not need to pass through the root. The path sum of a path is the sum of the node's values in the path. Given the `root` of a binary tree, return the maximum path sum of any non-empty path.",
  },
  {
    id: "60",
    title: "Serialize and Deserialize Binary Tree",
    difficulty: Difficulty.Hard,
    company: Company.Amazon,
    problemStatement: "Serialization is the process of converting a data structure or object into a sequence of bits so that it can be stored in a file or memory buffer, or transmitted across a network connection link to be reconstructed later in the same or another computer environment. Design an algorithm to serialize and deserialize a binary tree.",
  },
  // Tries
  {
    id: "61",
    title: "Implement Trie (Prefix Tree)",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "A trie (pronounced as 'try') or prefix tree is a tree data structure used to efficiently store and retrieve keys in a dataset of strings. There are various applications of this data structure, such as autocomplete and spellchecker. Implement the Trie class.",
  },
  {
    id: "62",
    title: "Design Add and Search Words Data Structure",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Design a data structure that supports adding new words and finding if a string matches any previously added string. Implement the WordDictionary class.",
  },
  {
    id: "63",
    title: "Word Search II",
    difficulty: Difficulty.Hard,
    company: Company.Microsoft,
    problemStatement: "Given an `m x n` board of characters and a list of strings `words`, return all words on the board. Each word must be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once in a word.",
  },
  // Heap / Priority Queue
  {
    id: "64",
    title: "Kth Largest Element in a Stream",
    difficulty: Difficulty.Easy,
    company: Company.Amazon,
    problemStatement: "Design a class to find the `k`th largest element in a stream. Note that it is the `k`th largest element in the sorted order, not the `k`th distinct element. Implement `KthLargest` class.",
  },
  {
    id: "65",
    title: "Last Stone Weight",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "You are given an array of integers `stones` where `stones[i]` is the weight of the `i`th stone. We are playing a game with the stones. On each turn, we choose the heaviest two stones and smash them together. Suppose the heaviest two stones have weights `x` and `y` with `x <= y`. The result of this smash is: If `x == y`, both stones are destroyed. If `x != y`, the stone of weight `x` is destroyed, and the stone of weight `y` has new weight `y - x`. At the end of the game, there is at most one stone left. Return the weight of the last remaining stone. If there are no stones left, return 0.",
  },
  {
    id: "66",
    title: "K Closest Points to Origin",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given an array of `points` where `points[i] = [xi, yi]` represents a point on the X-Y plane and an integer `k`, return the `k` closest points to the origin (0, 0).",
  },
  {
    id: "67",
    title: "Kth Largest Element in an Array",
    difficulty: Difficulty.Medium,
    company: Company.Apple,
    problemStatement: "Given an integer array `nums` and an integer `k`, return the `k`th largest element in the array.",
  },
  {
    id: "68",
    title: "Task Scheduler",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "Given a characters array `tasks`, representing the tasks a CPU needs to do, where each letter represents a different task. Tasks could be done in any order. Each task is done in one unit of time. For each unit of time, the CPU could complete either one task or just be idle. However, there is a non-negative integer `n` that represents the cooldown period between two same tasks (the same letter in the array), that is that there must be at least `n` units of time between any two same tasks. Return the least number of units of times that the CPU will take to finish all the given tasks.",
  },
  {
    id: "69",
    title: "Design Twitter",
    difficulty: Difficulty.Medium,
    company: Company.Netflix,
    problemStatement: "Design a simplified version of Twitter where users can post tweets, follow/unfollow another user, and is able to see the 10 most recent tweets in the user's news feed. Implement the `Twitter` class.",
  },
  // Backtracking
  {
    id: "70",
    title: "Subsets",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given an integer array `nums` of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets. Return the solution in any order.",
  },
  {
    id: "71",
    title: "Combination Sum",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Given an array of distinct integers `candidates` and a target integer `target`, return a list of all unique combinations of `candidates` where the chosen numbers sum to `target`. You may return the combinations in any order.",
  },
  {
    id: "72",
    title: "Permutations",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "Given an array `nums` of distinct integers, return all the possible permutations. You can return the answer in any order.",
  },
  {
    id: "73",
    title: "Subsets II",
    difficulty: Difficulty.Medium,
    company: Company.General,
    problemStatement: "Given an integer array `nums` that may contain duplicates, return all possible subsets (the power set). The solution set must not contain duplicate subsets. Return the solution in any order.",
  },
  {
    id: "74",
    title: "Combination Sum II",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "Given a collection of candidate numbers (`candidates`) and a target number (`target`), find all unique combinations in `candidates` where the candidate numbers sum to `target`. Each number in `candidates` may only be used once in the combination.",
  },
  {
    id: "75",
    title: "Word Search",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given an `m x n` grid of characters `board` and a string `word`, return `true` if `word` exists in the grid. The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.",
  },
  {
    id: "76",
    title: "Palindrome Partitioning",
    difficulty: Difficulty.Medium,
    company: Company.Apple,
    problemStatement: "Given a string `s`, partition `s` such that every substring of the partition is a palindrome. Return all possible palindrome partitioning of `s`.",
  },
  {
    id: "77",
    title: "Letter Combinations of a Phone Number",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order. A mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.",
  },
  // Graphs
  {
    id: "78",
    title: "Number of Islands",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "Given an `m x n` 2D binary grid `grid` which represents a map of '1's (land) and '0's (water), return the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.",
  },
  {
    id: "79",
    title: "Clone Graph",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given a reference of a node in a connected undirected graph. Return a deep copy (clone) of the graph.",
  },
  {
    id: "80",
    title: "Max Area of Island",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "You are given an `m x n` binary matrix `grid`. An island is a group of `1`'s (representing land) connected 4-directionally (horizontal or vertical.) You may assume all four edges of the grid are surrounded by water. The area of an island is the number of cells with a value `1` in the island. Return the maximum area of an island in `grid`. If there is no island, return 0.",
  },
  {
    id: "81",
    title: "Pacific Atlantic Water Flow",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "There is an `m x n` rectangular island that borders both the Pacific Ocean and the Atlantic Ocean. The Pacific Ocean touches the island's left and top edges, and the Atlantic Ocean touches the island's right and bottom edges. The island is partitioned into a grid of square cells. You are given an `m x n` integer matrix `heights` where `heights[r][c]` represents the height above sea level of the cell at coordinate `(r, c)`. Return a 2D list of grid coordinates `result` where `result[i] = [ri, ci]` denotes that rain water can flow from cell `(ri, ci)` to both the Pacific and Atlantic oceans.",
  },
  {
    id: "82",
    title: "Surrounded Regions",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "Given an `m x n` matrix `board` containing `'X'` and `'O'`, capture all regions that are 4-directionally surrounded by `'X'`. A region is captured by flipping all `'O'`s into `'X'`s in that surrounded region.",
  },
  {
    id: "83",
    title: "Rotting Oranges",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "You are given an `m x n` grid where each cell can have one of three values: 0 representing an empty cell, 1 representing a fresh orange, or 2 representing a rotten orange. Every minute, any fresh orange that is 4-directionally adjacent to a rotten orange becomes rotten. Return the minimum number of minutes that must elapse until no cell has a fresh orange. If this is impossible, return -1.",
  },
  {
    id: "84",
    title: "Walls and Gates",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "You are given a `m x n` grid `rooms` initialized with these three possible values: -1 A wall or an obstacle. 0 A gate. INF Infinity means an empty room. Fill each empty room with the distance to its nearest gate. If it is impossible to reach a gate, it should be filled with INF.",
  },
  {
    id: "85",
    title: "Course Schedule",
    difficulty: Difficulty.Medium,
    company: Company.General,
    problemStatement: "There are a total of `numCourses` courses you have to take, labeled from 0 to `numCourses - 1`. You are given an array `prerequisites` where `prerequisites[i] = [ai, bi]` indicates that you must take course `bi` first if you want to take course `ai`. Return `true` if you can finish all courses. Otherwise, return `false`.",
  },
  {
    id: "86",
    title: "Course Schedule II",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "There are a total of `numCourses` courses you have to take, labeled from 0 to `numCourses - 1`. You are given an array `prerequisites` where `prerequisites[i] = [ai, bi]` indicates that you must take course `bi` first if you want to take course `ai`. Return the ordering of courses you should take to finish all courses. If there are many valid answers, return any of them. If it is impossible to finish all courses, return an empty array.",
  },
  {
    id: "87",
    title: "Redundant Connection",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "In this problem, a tree is an undirected graph that is connected and has no cycles. You are given a graph that started as a tree with `n` nodes labeled from 1 to `n`, with one additional edge added. The added edge has two different vertices chosen from 1 to `n`, and was not an edge that already existed. The graph is represented as an array `edges` of length `n` where `edges[i] = [ai, bi]` indicates that there is an edge between nodes `ai` and `bi` in the graph. Return an edge that can be removed so that the resulting graph is a tree of `n` nodes.",
  },
  {
    id: "88",
    title: "Number of Connected Components",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "You have a graph of `n` nodes. You are given an integer `n` and an array `edges` where `edges[i] = [ai, bi]` indicates that there is an edge between `ai` and `bi` in the graph. Return the number of connected components in the graph.",
  },
  {
    id: "89",
    title: "Graph Valid Tree",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "You have a graph of `n` nodes labeled from 0 to `n - 1`. You are given an integer `n` and a list of `edges` where `edges[i] = [ai, bi]` indicates that there is an undirected edge between nodes `ai` and `bi`. Return `true` if the edges of the given graph make up a valid tree, and `false` otherwise.",
  },
  // Advanced Graphs
  {
    id: "90",
    title: "Cheapest Flights Within K Stops",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "There are `n` cities connected by some number of flights. You are given an array `flights` where `flights[i] = [fromi, toi, pricei]` indicates that there is a flight from city `fromi` to city `toi` with cost `pricei`. You are also given three integers `src`, `dst`, and `k`, return the cheapest price from `src` to `dst` with at most `k` stops. If there is no such route, return -1.",
  },
  {
    id: "91",
    title: "Network Delay Time",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "You are given a network of `n` nodes, labeled from 1 to `n`. You are also given `times`, a list of travel times as directed edges `times[i] = (ui, vi, wi)`, where `ui` is the source node, `vi` is the target node, and `wi` is the time it takes for a signal to travel from source to target. We will send a signal from a given node `k`. Return the time it takes for all `n` nodes to receive the signal. If it is impossible for all `n` nodes to receive the signal, return -1.",
  },
  {
    id: "92",
    title: "Min Cost to Connect All Points",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "You are given an array `points` representing integer coordinates of some points on a 2D-plane, where `points[i] = [xi, yi]`. The cost of connecting two points `[xi, yi]` and `[xj, yj]` is the manhattan distance between them: `|xi - xj| + |yi - yj|`. Return the minimum cost to make all points connected. All points are connected if there is exactly one simple path between any two points.",
  },
  {
    id: "93",
    title: "Reconstruct Itinerary",
    difficulty: Difficulty.Hard,
    company: Company.Meta,
    problemStatement: "You are given a list of airline `tickets` where `tickets[i] = [fromi, toi]` represent the departure and the arrival airports of one flight. Reconstruct the itinerary in order and return it. All of the tickets belong to a man who departs from `\"JFK\"`. Thus, the itinerary must begin with `\"JFK\"`. If there are multiple valid itineraries, you should return the itinerary that has the smallest lexical order when read as a single string.",
  },
  // 1-D Dynamic Programming
  {
    id: "94",
    title: "Climbing Stairs",
    difficulty: Difficulty.Easy,
    company: Company.Adobe,
    problemStatement: "You are climbing a staircase. It takes `n` steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
  },
  {
    id: "95",
    title: "Min Cost Climbing Stairs",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "You are given an integer array `cost` where `cost[i]` is the cost of `i`-th step on a staircase. Once you pay the cost, you can either climb one or two steps. You can either start from the step with index 0, or the step with index 1. Return the minimum cost to reach the top of the floor.",
  },
  {
    id: "96",
    title: "House Robber",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and it will automatically contact the police if two adjacent houses were broken into on the same night. Given an integer array `nums` representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.",
  },
  {
    id: "97",
    title: "House Robber II",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "You are a professional robber planning to rob houses along a street. All houses at this place are arranged in a circle. That means the first house is the neighbor of the last one. Meanwhile, adjacent houses have a security system connected, and it will automatically contact the police if two adjacent houses were broken into on the same night. Given an integer array `nums` representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.",
  },
  {
    id: "98",
    title: "Longest Palindromic Substring",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Given a string `s`, return the longest palindromic substring in `s`.",
  },
  {
    id: "99",
    title: "Palindromic Substrings",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given a string `s`, return the number of palindromic substrings in it. A string is a palindrome when it reads the same backward as forward. A substring is a contiguous sequence of characters within the string.",
  },
  {
    id: "100",
    title: "Decode Ways",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "A message containing letters from A-Z can be encoded into numbers using the following mapping: 'A' -> '1', 'B' -> '2', ..., 'Z' -> '26'. To decode an encoded message, all the digits must be grouped then mapped back into letters using the reverse of the mapping above (there may be multiple ways). Given a string `s` containing only digits, return the number of ways to decode it.",
  },
  {
    id: "101",
    title: "Coin Change",
    difficulty: Difficulty.Medium,
    company: Company.Netflix,
    problemStatement: "You are given an integer array `coins` representing coins of different denominations and an integer `amount` representing a total amount of money. Return the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.",
  },
  {
    id: "102",
    title: "Maximum Product Subarray",
    difficulty: Difficulty.Medium,
    company: Company.Apple,
    problemStatement: "Given an integer array `nums`, find a subarray that has the largest product, and return the product.",
  },
  {
    id: "103",
    title: "Word Break",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Given a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words.",
  },
  {
    id: "104",
    title: "Longest Increasing Subsequence",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "Given an integer array `nums`, return the length of the longest strictly increasing subsequence.",
  },
  {
    id: "105",
    title: "Partition Equal Subset Sum",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given an integer array `nums`, return `true` if you can partition the array into two subsets such that the sum of the elements in both subsets is equal or `false` otherwise.",
  },
  // 2-D Dynamic Programming
  {
    id: "106",
    title: "Unique Paths",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "There is a robot on an `m x n` grid. The robot is initially located at the top-left corner (i.e., `grid[0][0]`). The robot tries to move to the bottom-right corner (i.e., `grid[m - 1][n - 1]`). The robot can only move either down or right at any point in time. Given the two integers `m` and `n`, return the number of possible unique paths that the robot can take to reach the bottom-right corner.",
  },
  {
    id: "107",
    title: "Longest Common Subsequence",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Given two strings `text1` and `text2`, return the length of their longest common subsequence. If there is no common subsequence, return 0. A subsequence of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.",
  },
  {
    id: "108",
    title: "Best Time to Buy and Sell Stock with Cooldown",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "You are given an array `prices` where `prices[i]` is the price of a given stock on the `i`-th day. Find the maximum profit you can achieve. You may complete as many transactions as you like (i.e., buy one and sell one share of the stock multiple times) with the following restrictions: After you sell your stock, you cannot buy stock on the next day (i.e., cooldown one day).",
  },
  {
    id: "109",
    title: "Coin Change II",
    difficulty: Difficulty.Medium,
    company: Company.Netflix,
    problemStatement: "You are given an integer array `coins` representing coins of different denominations and an integer `amount` representing a total amount of money. Return the number of combinations that make up that amount. If that amount of money cannot be made up by any combination of the coins, return 0.",
  },
  {
    id: "110",
    title: "Target Sum",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "You are given an integer array `nums` and an integer `target`. You want to build an expression out of `nums` by adding one of the symbols `'+'` and `'-'` before each integer in `nums` and then concatenate all the integers. Return the number of different expressions that you can build, which evaluates to `target`.",
  },
  {
    id: "111",
    title: "Interleaving String",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "Given strings `s1`, `s2`, and `s3`, find whether `s3` is formed by an interleaving of `s1` and `s2`. An interleaving of two strings `s` and `t` is a configuration where `s` and `t` are divided into `n` and `m` non-empty substrings respectively.",
  },
  {
    id: "112",
    title: "Edit Distance",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "Given two strings `word1` and `word2`, return the minimum number of operations required to convert `word1` to `word2`. You have the following three operations permitted on a word: Insert a character, Delete a character, Replace a character.",
  },
  {
    id: "113",
    title: "Burst Balloons",
    difficulty: Difficulty.Hard,
    company: Company.Google,
    problemStatement: "You are given `n` balloons, indexed from 0 to `n - 1`. Each balloon is painted with a number on it represented by an array `nums`. You are asked to burst all the balloons. If you burst the `i`-th balloon, you will get `nums[i - 1] * nums[i] * nums[i + 1]` coins. Here `nums[i - 1]` and `nums[i + 1]` are the adjacent balloons of the `i`-th balloon. After the burst, the `i - 1`-th and `i + 1`-th balloons become adjacent. Return the maximum coins you can collect by bursting the balloons wisely.",
  },
  {
    id: "114",
    title: "Distinct Subsequences",
    difficulty: Difficulty.Hard,
    company: Company.Apple,
    problemStatement: "Given two strings `s` and `t`, return the number of distinct subsequences of `s` which equals `t`. The test cases are generated so that the answer fits on a 32-bit signed integer.",
  },
  // Greedy
  {
    id: "115",
    title: "Maximum Subarray",
    difficulty: Difficulty.Medium,
    company: Company.General,
    problemStatement: "Given an integer array `nums`, find the subarray with the largest sum, and return its sum.",
  },
  {
    id: "116",
    title: "Jump Game",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "You are given an integer array `nums`. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position. Return `true` if you can reach the last index, or `false` otherwise.",
  },
  {
    id: "117",
    title: "Jump Game II",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "You are given a 0-indexed array of integers `nums` of length `n`. You are initially positioned at `nums[0]`. Each element `nums[i]` represents the maximum length of a forward jump from index `i`. Return the minimum number of jumps to reach `nums[n - 1]`.",
  },
  {
    id: "118",
    title: "Gas Station",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "There are `n` gas stations along a circular route, where the amount of gas at the `i`-th station is `gas[i]`. You have a car with an unlimited gas tank and it costs `cost[i]` of gas to travel from the `i`-th station to its next `(i + 1)`-th station. You begin the journey with an empty tank at one of the gas stations. Given two integer arrays `gas` and `cost`, return the starting gas station's index if you can travel around the circuit once in the clockwise direction, otherwise return -1.",
  },
  {
    id: "119",
    title: "Hand of Straights",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Alice has some number of cards and she wants to rearrange the cards into groups of `groupSize` consecutive cards. Given an integer array `hand` where `hand[i]` is the value written on the `i`-th card and an integer `groupSize`, return `true` if she can rearrange the cards, or `false` otherwise.",
  },
  {
    id: "120",
    title: "Merge Triplets to Form Target Triplet",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "A triplet is an array of three integers. You are given a 2D integer array `triplets`, where `triplets[i] = [ai, bi, ci]` represents the `i`-th triplet. You are also given an integer array `target = [x, y, z]` that represents the triplet we want to obtain. To obtain `target`, you may apply the following operation on `triplets` any number of times: Choose two indices `i` and `j` and update `triplets[j]` to become `[max(ai, aj), max(bi, bj), max(ci, cj)]`. Return `true` if it is possible to obtain the `target` triplet `[x, y, z]` as an element of `triplets`, or `false` otherwise.",
  },
  {
    id: "121",
    title: "Partition Labels",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "You are given a string `s`. We want to partition the string into as many parts as possible so that each letter appears in at most one part. Notice that the partition is done so that after concatenating all the parts in order, the resultant string should be `s`. Return a list of integers representing the size of these parts.",
  },
  // Intervals
  {
    id: "122",
    title: "Insert Interval",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "You are given an array of non-overlapping intervals `intervals` where `intervals[i] = [starti, endi]` represent the start and the end of the `i`-th interval and `intervals` is sorted in ascending order by `starti`. You are also given an interval `newInterval = [start, end]` that represents the start and end of another interval. Insert `newInterval` into `intervals` such that `intervals` is still sorted in ascending order by `starti` and `intervals` still does not have any overlapping intervals. Return `intervals` after the insertion.",
  },
  {
    id: "123",
    title: "Merge Intervals",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "Given an array of `intervals` where `intervals[i] = [starti, endi]`, merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.",
  },
  {
    id: "124",
    title: "Non-overlapping Intervals",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given an array of intervals `intervals` where `intervals[i] = [starti, endi]`, return the minimum number of intervals you need to remove to make the rest of the intervals non-overlapping.",
  },
  {
    id: "125",
    title: "Meeting Rooms",
    difficulty: Difficulty.Easy,
    company: Company.Amazon,
    problemStatement: "Given an array of meeting time intervals `intervals` where `intervals[i] = [starti, endi]`, determine if a person could attend all meetings.",
  },
  {
    id: "126",
    title: "Meeting Rooms II",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "Given an array of meeting time intervals `intervals` where `intervals[i] = [starti, endi]`, return the minimum number of conference rooms required.",
  },
  {
    id: "127",
    title: "Minimum Interval to Include Each Query",
    difficulty: Difficulty.Hard,
    company: Company.Netflix,
    problemStatement: "You are given a 2D integer array `intervals`, where `intervals[i] = [lefti, righti]` describes the `i`-th interval for all `i` from 0 to `n - 1`. You are also given an integer array `queries`. The answer to the `j`-th query is the size of the smallest interval `i` such that `lefti <= queries[j] <= righti`. If no such interval exists, the answer is -1. Return an array containing the answers to the queries.",
  },
  // Math & Geometry
  {
    id: "128",
    title: "Rotate Image",
    difficulty: Difficulty.Medium,
    company: Company.Amazon,
    problemStatement: "You are given an `n x n` 2D `matrix` representing an image, rotate the image by 90 degrees (clockwise). You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.",
  },
  {
    id: "129",
    title: "Spiral Matrix",
    difficulty: Difficulty.Medium,
    company: Company.Microsoft,
    problemStatement: "Given an `m x n` `matrix`, return all elements of the `matrix` in spiral order.",
  },
  {
    id: "130",
    title: "Set Matrix Zeroes",
    difficulty: Difficulty.Medium,
    company: Company.Meta,
    problemStatement: "Given an `m x n` integer `matrix`, if an element is 0, set its entire row and column to 0's. You must do it in-place.",
  },
  {
    id: "131",
    title: "Happy Number",
    difficulty: Difficulty.Easy,
    company: Company.Google,
    problemStatement: "Write an algorithm to determine if a number `n` is happy. A happy number is a number defined by the following process: Starting with any positive integer, replace the number by the sum of the squares of its digits. Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1. Those numbers for which this process ends in 1 are happy.",
  },
  {
    id: "132",
    title: "Plus One",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "You are given a large integer represented as an integer array `digits`, where each `digits[i]` is the `i`-th digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's. Increment the large integer by one and return the resulting array of digits.",
  },
  {
    id: "133",
    title: "Pow(x, n)",
    difficulty: Difficulty.Medium,
    company: Company.Apple,
    problemStatement: "Implement `pow(x, n)`, which calculates `x` raised to the power `n` (i.e., `x^n`).",
  },
  {
    id: "134",
    title: "Multiply Strings",
    difficulty: Difficulty.Medium,
    company: Company.Adobe,
    problemStatement: "Given two non-negative integers `num1` and `num2` represented as strings, return the product of `num1` and `num2`, also represented as a string. Note: You must not use any built-in BigInteger library or convert the inputs to integer directly.",
  },
  // Bit Manipulation
  {
    id: "135",
    title: "Single Number",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "Given a non-empty array of integers `nums`, every element appears twice except for one. Find that single one. You must implement a solution with a linear runtime complexity and use only constant extra space.",
  },
  {
    id: "136",
    title: "Number of 1 Bits",
    difficulty: Difficulty.Easy,
    company: Company.Microsoft,
    problemStatement: "Write a function that takes the binary representation of a positive integer and returns the number of set bits it has (also known as the Hamming weight).",
  },
  {
    id: "137",
    title: "Counting Bits",
    difficulty: Difficulty.Easy,
    company: Company.Meta,
    problemStatement: "Given an integer `n`, return an array `ans` of length `n + 1` such that for each `i` (0 <= i <= n), `ans[i]` is the number of 1's in the binary representation of `i`.",
  },
  {
    id: "138",
    title: "Reverse Bits",
    difficulty: Difficulty.Easy,
    company: Company.Apple,
    problemStatement: "Reverse bits of a given 32 bits unsigned integer.",
  },
  {
    id: "139",
    title: "Missing Number",
    difficulty: Difficulty.Easy,
    company: Company.Amazon,
    problemStatement: "Given an array `nums` containing `n` distinct numbers in the range `[0, n]`, return the only number in the range that is missing from the array.",
  },
  {
    id: "140",
    title: "Sum of Two Integers",
    difficulty: Difficulty.Medium,
    company: Company.Google,
    problemStatement: "Given two integers `a` and `b`, return the sum of the two integers without using the operators `+` and `-`.",
  },
  {
    id: "141",
    title: "Reverse Integer",
    difficulty: Difficulty.Medium,
    company: Company.Netflix,
    problemStatement: "Given a signed 32-bit integer `x`, return `x` with its digits reversed. If reversing `x` causes the value to go outside the signed 32-bit integer range `[-2^31, 2^31 - 1]`, then return 0.",
  },
  // Extra / Miscellaneous
  {
    id: "142",
    title: "Pascal's Triangle",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "Given an integer `numRows`, return the first numRows of Pascal's triangle."
  },
  {
    id: "143",
    title: "Excel Sheet Column Number",
    difficulty: Difficulty.Easy,
    company: Company.Microsoft,
    problemStatement: "Given a string `columnTitle` that represents the column title as it appears in an Excel sheet, return its corresponding column number."
  },
  {
    id: "144",
    title: "Majority Element",
    difficulty: Difficulty.Easy,
    company: Company.Adobe,
    problemStatement: "Given an array `nums` of size `n`, return the majority element. The majority element is the element that appears more than `⌊n / 2⌋` times. You may assume that the majority element always exists in the array."
  },
  {
    id: "145",
    title: "Isomorphic Strings",
    difficulty: Difficulty.Easy,
    company: Company.Google,
    problemStatement: "Given two strings `s` and `t`, determine if they are isomorphic. Two strings `s` and `t` are isomorphic if the characters in `s` can be replaced to get `t`."
  },
  {
    id: "146",
    title: "Contains Duplicate II",
    difficulty: Difficulty.Easy,
    company: Company.Amazon,
    problemStatement: "Given an integer array `nums` and an integer `k`, return `true` if there are two distinct indices `i` and `j` in the array such that `nums[i] == nums[j]` and `abs(i - j) <= k`."
  },
  {
    id: "147",
    title: "Summary Ranges",
    difficulty: Difficulty.Easy,
    company: Company.Meta,
    problemStatement: "You are given a sorted unique integer array `nums`. Return the smallest sorted list of ranges that cover all the numbers in the array exactly."
  },
  {
    id: "148",
    title: "Move Zeroes",
    difficulty: Difficulty.Easy,
    company: Company.General,
    problemStatement: "Given an integer array `nums`, move all `0`'s to the end of it while maintaining the relative order of the non-zero elements. Note that you must do this in-place without making a copy of the array."
  },
  {
    id: "149",
    title: "Range Sum Query - Immutable",
    difficulty: Difficulty.Easy,
    company: Company.Netflix,
    problemStatement: "Given an integer array `nums`, handle multiple queries of the following type: Calculate the sum of the elements of `nums` between indices `left` and `right` inclusive where `left <= right`. Implement the `NumArray` class."
  },
  {
    id: "150",
    title: "Fizz Buzz",
    difficulty: Difficulty.Easy,
    company: Company.Apple,
    problemStatement: "Given an integer `n`, return a string array `answer` (1-indexed) where `answer[i]` is 'FizzBuzz' if `i` is divisible by 3 and 5, 'Fizz' if `i` is divisible by 3, 'Buzz' if `i` is divisible by 5, and `i` (as a string) if none of the above conditions are true."
  }
];